kind: pipeline
name: build
steps:
- name: lint
  image: node
  commands:
  - npm install
  - npm run lint

  when:
    branch:
    - master
    - develop
    - feature/*
    event:
    - push

---

kind: pipeline
name: create-lambda
steps:
- name: zip
  image: alpine
  commands:
  - apk update && apk add zip
  - zip -r target.zip src node_modules package.json

- name: create
  image: lorentzca/aws
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:  ap-northeast-1
  commands: 
  - aws lambda create-function 
    --function-name ${DRONE_LAMBDA_FUNCTION_NAME}
    --runtime nodejs8.10
    --role ${DRONE_LAMBDA_ROLE_ARN}
    --handler src/index.handler
    --environment Variables={TABLE_NAME=SandboxTable,TZ=Asia/Tokyo}
    --layers ${DRONE_LAYER_ARN}
    --zip-file fileb://./target.zip
  when:
    instance:
      include:
      - localhost

# ---
# kind: pipeline
# name: deploy
# steps:
# - name: zip
#   image: alpine
#   commands:
#   - apk update && apk add zip
#   - zip -r target.zip src node_modules package.json

# - name: deploy-lambda
#   image: lorentzca/aws
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     AWS_DEFAULT_REGION:  ap-northeast-1
#   commands:
#   - aws lambda update-function-code --function-name alexa-toilet-training --zip-file fileb://./target.zip
#   when:
#     branch:
#     - master
#     event:
#     - push

# - name: deploy-lambda-publish
#   image: lorentzca/aws
#   environment:
#     AWS_ACCESS_KEY_ID:
#       from_secret: AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     AWS_DEFAULT_REGION:  ap-northeast-1
#   commands:
#   - aws lambda update-function-code --function-name alexa-toilet-training --zip-file fileb://./target.zip 
#   - aws lambda publish-version --function-name alexa-toilet-training --description ${DRONE_TAG}
#   when:
#     event:
#     - tag
