---
kind: pipeline
name: build
steps:
- name: lint
  image: node
  commands:
  - npm install
  - npm run lint

trigger:
  branch:
  - master
  - develop
  - feature/*
  event:
  - push

---
kind: pipeline
name: deploy
steps:

- name: zip
  image: alpine
  commands:
  - apk update && apk add zip
  - zip -r target.zip src node_modules package.json

- name: upload
  image: plugins/s3
  settings:
    bucket: alexa-toilet-training
    region: ap-northeast-1
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    source: target.zip
    target: /build

# - name: deploy-lambda
#   image: omerxx/drone-lambda-plugin
#   settings:
#     pull: true
#     function_name: alexa-toilet-training
#     s3_bucket: alexa-toilet-training
#     file_name: build/target.zip

trigger:
  branch:
  - master
  event:
  - push
