---
kind: pipeline
name: default
steps:
- name: lint
  image: node
  commands:
  - npm install
  - npm run lint

- name: zip
  image: alpine
  commands:
  - apk update && apk add zip
  - zip -r target.zip src node_modules package.json

- name: upload
  image: plugins/s3
  settings:
    bucket: alexa-toilet-training
    region: ap-northeast-1
    access_key:
      from_secret: ACCESS_KEY
    secret_key:
      from_secret: SECRET_KEY
    source: target.zip
    target: /build

# - name: deploy-lambda
#   image: omerxx/drone-lambda-plugin
#   pull: true
#   access_key: ACCESS_KEY
#   secret_key: SECRET_KEY
#   function_name: alexa-toilet-training
#   s3_bucket: alexa-toilet-training
#   file_name: build/target.zip

trigger:
  branch:
  - master
  - develop
  - feature/*
  event:
  - push
