---
kind: pipeline
name: build
steps:
- name: lint
  image: node
  commands:
  - npm install
  - npm run lint
  when:
    branch:
    - master
    - develop
    - feature/*
    event:
    - push

---
kind: pipeline
name: deploy
steps:
- name: zip
  image: alpine
  commands:
  - apk update && apk add zip
  - zip -r target.zip src node_modules package.json

- name: deploy-lambda
  image: lorentzca/aws
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:  ap-northeast-1
  commands:
  - aws lambda update-function-code --function-name alexa-toilet-training --zip-file fileb://./target.zip
  when:
    branch:
    - master
    event:
    - push

- name: deploy-lambda-publish
  image: lorentzca/aws
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:  ap-northeast-1
  commands:
  - aws lambda update-function-code --function-name alexa-toilet-training --zip-file fileb://./target.zip --publish --revision-id ${DRONE_TAG}
  when:
    event:
    - tag
