---
kind: pipeline
name: default
steps:
- name: lint&zip
  image: node
  commands:
  - npm install
  - npm run lint
  - zip -r target.zip src node_modules package.json

- name: upload
  image: plugins/s3
  settings:
    bucket: alexa-toilet-training
    access_key: ACCESS_KEY
    secret_key: SECRET_KEY
    source: target.zip
    target: /build

trigger:
  branch:
  - master
  - develop
  - feature/*
  event:
  - push
